# Generated by Django 2.1.1 on 2020-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.IntegerField(default=0)),
                ('desc_archivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=0)),
                ('qna', models.CharField(max_length=2)),
                ('fecha_envio', models.DateTimeField(verbose_name='Fecha de Quincena')),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=1)),
                ('art74_fed', models.CharField(choices=[('A', 'ARTICULO 74'), ('F', 'FEDERAL')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Remesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_remesas', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('fecha_validacion', models.DateTimeField(verbose_name='Fecha de Vañidacion')),
                ('fecha_carga', models.DateTimeField(verbose_name='Fecha de carga')),
                ('tipo_archivo', models.CharField(max_length=1)),
                ('archivo', models.CharField(max_length=250)),
                ('registros', models.IntegerField(default=0)),
                ('observaciones', models.CharField(max_length=250)),
                ('etiqueta_envio', models.CharField(max_length=30)),
                ('archivo_error', models.CharField(max_length=250)),
                ('registros_error', models.IntegerField(default=0)),
                ('estatus', models.CharField(max_length=1)),
                ('id_tipo_nom', models.CharField(max_length=2)),
                ('fecha_agregacion', models.IntegerField(default=0)),
                ('tabla_staging', models.CharField(max_length=50)),
                ('tabla_ods', models.CharField(max_length=50)),
                ('lista_urs', models.CharField(max_length=1024)),
                ('art74_fed', models.CharField(max_length=1)),
            ],
        ),
    ]
